#!/usr/bin/env php
<?php

/**
 * Signal fatal and exit
 *
 * @param string $message
 */
function fatal($message)
{
    echo "$message\n";
    exit(1);
}

/**
 * Try to fetch the page with the video on
 *
 * @param string $title
 *
 * @return HttpMessage
 */
function fetch($title)
{
    $req = new HttpRequest();
    $req->setHeaders(
        array(
            'User-Agent' => 'Mozilla/5.0(iPad; U; CPU iPhone OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B314 Safari/531.21.10'
        )
    );
    $req->setUrl(
        sprintf(
            'http://www.infoq.com/presentations/%s',
            urlencode($title)
        )
    );

    return $req->send();
}

/**
 * @param HttpMessage $res
 */
function download(HttpMessage $res)
{
    $body = $res->getBody();

    if (preg_match('/http:\/\/.*?.mp4/', $body, $matches)) {
        list($videoUrl) = $matches;

        passthru(sprintf('curl -O %s', $videoUrl));
    } else {
        fatal("Cannot find video URL! :(");
    }
}

list($SCRIPT, $title) = $_SERVER['argv'];

if (!$title) {
    fatal("Usage: quids The-Video-Url-Title");
}

try {
    $res = fetch($title);
    if ($res->getResponseCode() != 200) {
        fatal("Ooops!  Couldn't find that video, check your title matches the name in the URL");
    }
    download($res);
} catch (Exception $e) {
    fatal($e->getMessage());
}

